services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: mmd-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: mmd-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  spark:
    image: apache/spark:3.5.0
    container_name: mmd-spark
    depends_on:
      - kafka
    environment:
      HOME: /tmp
      SPARK_SUBMIT_OPTS: "-Divy.cache.dir=/tmp/.ivy2/cache -Divy.home=/tmp/.ivy2"
    entrypoint: ["/bin/sh", "-c"]
    command:
      - >
        mkdir -p /tmp/.ivy2/cache;
        /opt/spark/bin/spark-submit
        --conf spark.jars.ivy=/tmp/.ivy2
        --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,io.delta:delta-spark_2.12:3.2.0
        --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension
        --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
        /opt/spark_streaming/bronze_writer.py
    volumes:
      - ../spark_streaming:/opt/spark_streaming
      - ../lakehouse:/opt/lakehouse
